### ISSUE TITLE
limit ability for patrons to schedule pickups to only patrons with waiting holds

### ISSUE THREAD

**Issue by donnabws** [bywatersolutions/koha-plugin-curbside-pickup#1]
There are situations where patrons should not be able to schedule a pickup request from the OPAC unless they have holds waiting for pickup.

**Comment by mkstephens** [comment]
There are also situations where libraries may use this plugin for patrons to schedule other types of pickups and appointments not related to holds. If added, this ability to limit should be an option in the configuration.

**Comment by tomascohen** [comment]
Old plugin version request.
