### ISSUE TITLE
Option to remove "patron has arrived" button by libary

### ISSUE THREAD

**Issue by lisettescheer** [bywatersolutions/koha-plugin-curbside-pickup#10]
Some branches aren't using the "patron has arrived" button because our workflow currently takes all our items out to the plaza and have them set up on a table during our intervals. 
It would be nice if as part of the setup, each branch could select if they needed the "patron has arrived" option for their workflow. It might confuse patrons if they think they have to check in when it isn't needed.

**Comment by mkstephens** [comment]
Some custom jQuery or CSS might work to hide the button, but agree that this should be something added to the configuration settings to turn this feature on or off.

**Comment by tomascohen** [comment]
Old plugin version request.
