### ISSUE TITLE
Pickups showing up in OPAC after marked as delivered

### ISSUE THREAD

**Issue by mkstephens** [bywatersolutions/koha-plugin-curbside-pickup#12]
This is an issue that was reported to the Koha listserv: https://lists.katipo.co.nz/pipermail/koha/2020-September/055146.html

Regardless of what stages the pickup goes through in the tool, the pickup continues to show up in the patron's account after it has been marked as delivered. The only way for a patron to schedule a new pickup on the same day is to cancel the pickup that has already happened. When a patron does this, the record is also deleted from the "delivered today" tab in the staff client.

The CURBSIDE notice is also affected, as noted in the post to the Koha listserv.

**Comment by tomascohen** [comment]
Old plugin version request.
