### ISSUE TITLE
Pickups showing up on both "staged & ready" and "delivered" tabs when marked as delivered from "staged & ready"

### ISSUE THREAD

**Issue by mkstephens** [bywatersolutions/koha-plugin-curbside-pickup#13]
There is a "marked as delivered" button on the "staged & ready" tab that pushes a pickup straight to delivered, skipping over the "patron is outside" stage. This is super-helpful for libraries that do not need or want to use the "patron is outside" stage.

When the "marked as delivered" button is clicked from the "staged & ready" tab, the pickup is copied over to delivered and continues to show up on the "staged & ready" tab. The only way to get it to disappear from "staged & ready" is to pass it through the "patron is outside" stage, which defeats the purpose of making the "marked as delivered" button available from staged & ready.

**Comment by lisettescheer** [comment]
We are also having a problem with this, especially if another hold comes in for that patron then it will show as staged and ready after everything else was delivered.

**Comment by tomascohen** [comment]
Old plugin version request.
