### ISSUE TITLE
Notification mail to user

### ISSUE THREAD

**Issue by lrosas07** [bywatersolutions/koha-plugin-curbside-pickup#14]
Hello, it would be a great improve for us if the user receive a confirmation email of the date and hour he/she have the appointment. In our library we send an email with the instructions to enter to the building and to confirm there is no problem in the process.

**Comment by lisettescheer** [comment]
You can create a notice with the code:
CURBSIDE
And create a notice. I don't know if you have to set a cron to run for it. BWS might have done it for us when I told them I was setting it up?
I don't remember where I got the below notice and then I made a couple changes for our branch:
 
[%- USE KohaDates -%]
[%- SET cp = curbside_pickup -%]

You have a curbside pickup scheduled for [% cp.scheduled_pickup_datetime | $KohaDates with_hours => 1 %] at [% cp.library.branchname %].

Any holds waiting for you at the pickup time will be included in this pickup. At this time, that list includes:
[%- FOREACH h IN cp.patron.holds %]
    [%- IF h.branchcode == cp.branchcode && h.found == 'W' %]
* [% h.biblio.title %], [% h.biblio.author %] ([% h.item.barcode %])
    [%- END %]
[%- END %]

Once you have arrived, please go to the table we have setup on the front plaza to pick up your holds.

**Comment by lrosas07** [comment]
Many thanks for your answer, we are testing the system ;-) these days!

**Comment by hagud** [comment]
we have set up the latest version of this plguin, and it works fine however we're not able to configure the notification by mail, we have checked that notice CURBSIDE is configured... and we have also checked that hold preference message is activated at user lever.

what we're missing.. we have no crons configured specific for curbside..

any help will be welcomed!

**Comment by tomascohen** [comment]
Old plugin version request.
