### ISSUE TITLE
Pickup Location Picker inconsistency

### ISSUE THREAD

**Issue by lisettescheer** [bywatersolutions/koha-plugin-curbside-pickup#15]
If settings aren't allowing patrons to set their item pickup location, the plugin shouldn't allow patrons to set up curbside pickup at different locations (or it should be an option.)

**Comment by kylemhall** [comment]
I'm not sure I'm grokking you. Can you give me a bit more detail about the issue?

Thanks!

**Comment by lisettescheer** [comment]
No problem.
Our library consortium has turned off the ability in Koha for patron's to select their pickup location when placing holds (OPACAllowUserToChooseBranch.) This is because we want to reduce the number of people going to different branches to pick up their items. 
Having the ability to only allow people to select their home library for curbside pickup would allow for better consistency for multibranch systems.

**Comment by tomascohen** [comment]
Old plugin version request.
