### ISSUE TITLE
Limit of schedule of the day

### ISSUE THREAD

**Issue by lrosas07** [bywatersolutions/koha-plugin-curbside-pickup#16]
Hello, 

It would be great for our library to limit the time of the day you can pick up a curpside. We say aour users that they have to choose an hour 24 hours before the day but the system allow them to pick up a curpside for the afternoon of the same day. It woulb be great that the user can't pick up a curpside two hours before the library opens for example so we can now for sure how many people we will have this day.

**Comment by tomascohen** [comment]
Old plugin version request.
