### ISSUE TITLE
Notes in the curbside

### ISSUE THREAD

**Issue by lrosas07** [bywatersolutions/koha-plugin-curbside-pickup#18]
Hello,

It would be possible to have the field notes with more space to write the consults of the users? Now there is little space to write and we use it in order people can write the book they want or the questions they have.

Many thanks!

**Comment by CPkcook** [comment]
It would also be helpful if staff could add to the note field after the reservation has been made.

**Comment by tomascohen** [comment]
Old plugin version request.
