### ISSUE TITLE
Intranet schedule pickup button doesn't work correctly

### ISSUE THREAD

**Issue by PabloJones** [bywatersolutions/koha-plugin-curbside-pickup#19]
Hello! we have installed koha 19.11.05. Testing the plugin from the user screen, the shedule pickcup button, when clicked, the borrowernumber is not sent to the plugin, and shows the error "No pattern found with cardnumber.". Instead the categorycode is sent. This is the url sent to the plugin:
 http: //.../cgi-bin/koha/plugins/run.pl? class = Koha% 3A% 3APlugin% 3A% 3ACom% 3A% 3AByWaterSolutions% 3A% 3ACurbsidePickup & method = tool & action = find-patron & tab = schedule-pickup & borrowernumber = DOC.
DOC is the categorycode for teacher.
Is it a problem with my server
r Koha?
Browser used Firefox 82.0.2 (64bit).
Thank you!

From Trelew (Chubut) Argentina

**Comment by tomascohen** [comment]
Old plugin version request.
