### ISSUE TITLE
Patrons who are expired or blocked can have items delivered, but items do not check out

### ISSUE THREAD

**Issue by benjaminwd** [bywatersolutions/koha-plugin-curbside-pickup#22]
Patrons who are expired or blocked are still able to schedule pickups, and we are able to "deliver" them, but the items do not check out. There isn't any indication that this user is unable to check-out during the process, so staff end up delivering items that are not checked out. There should be some sort of indication that there is an issue with the checkout.

**Comment by tomascohen** [comment]
Old plugin version request.
