### ISSUE TITLE
Unstaged Holds Getting Checked Out

### ISSUE THREAD

**Issue by CPkcook** [bywatersolutions/koha-plugin-curbside-pickup#24]
We're having an issue where we stage all of a patron's holds that are available, but in the 20 minute window between when we staged the holds and the patron arrives, additional holds have been trapped. It would be nice if those didn't appear in the Staged & Ready tab automatically to avoid checking out items that are still in the building.

**Comment by tomascohen** [comment]
Old plugin version request.
