### ISSUE TITLE
Plugin generates a lot of log noise over a malformed version number 

### ISSUE THREAD

**Issue by lizrea** [bywatersolutions/koha-plugin-curbside-pickup#28]
We get a lot of noise in our logs such as the following: 

Argument "v1" isn't numeric in int at /usr/share/koha/lib/Koha/Plugins/Base.pm line 333.
It seems to stem from how the version was generated when the .kpz was created, as the version is what looks like a j2 variable in CurbsidePickup.pm. 

Removing the v from Koha/Plugin/Com/ByWaterSolutions/CurbsidePickup.pm on the $VERSION in the running plugin seems to quiet the noise (and the plugin still works, so that's nice).

**Comment by kylemhall** [comment]
Fixed by latest commit!

**Comment by kylemhall** [comment]
https://github.com/bywatersolutions/koha-plugin-curbside-pickup/commit/2492943314deb1f5c02229c5d94ee3d8a29074b8
