### ISSUE TITLE
set cutoff time for scheduling a pickup

### ISSUE THREAD

**Issue by donnabws** [bywatersolutions/koha-plugin-curbside-pickup#3]
Libraries would like the ability to enforce a cutoff time for scheduling appointments.  For instance, appointments must be scheduled 24 hours ahead, or by the end of business two days prior (pickups on thursday must be scheduled by Tuesday at 5).

**Comment by mkstephens** [comment]
This would be super-helpful! I'm afraid our staff will miss seeing pickups that are scheduled too close to the time of pickup. Next business day would be perfect for us -- 24 hours might be too excessive. It would be nice if staff could check for scheduled pickups at the beginning of a shift and have the confidence that no new pickups would be scheduled while they are engaged in their work.

**Comment by tomascohen** [comment]
Old plugin version request.
