### ISSUE TITLE
Issues on 21.05

### ISSUE THREAD

**Issue by JohnYorio** [bywatersolutions/koha-plugin-curbside-pickup#30]
Upgraded a system to 21.05 and curbside stopped working - the modal dialog stays on the screen spinning with "Loading curbside pickups" when a patron clicks "your curbside pickups" in the OPAC.

Tried to install to test on a clean 21.05 system and ran into some problems installing on 21.05.

It looks like CREATE TABLE `curbside_pickup_issues`  is in the CurbsidePickup.pm twice, one after the other. 

One of them includes an extra comma which causes some issues too:
FOREIGN KEY (curbside_pickup_id) REFERENCES curbside_pickups(id) ON DELETE CASCADE ON UPDATE CASCADE,

also creating the record in the letter table fails:
Koha::Plugin::Com::ByWaterSolutions::CurbsidePickup::install(): DBI Exception: DBD::mysql::db do failed: Column count doesn't match value count at row 1 [for Statement "
        INSERT INTO `letter` VALUES ('reserves','CURBSIDE','','Curbside pickup',0,'You have schedule a curbside pickup for <<branches.branchname>>','[%- USE KohaDates -%]\r\n[%- SET cp = curbside_pickup -%]\r\n\r\nYou have a curbside pickup scheduled for [% cp.scheduled_pickup_datetime | $KohaDates with_hours => 1 %] at [% cp.library.branchname %].\r\n\r\nAny holds waiting for you at the pickup time will be included in this pickup. At this time, that list includes:\r\n[%- FOREACH h IN cp.patron.holds %]\r\n    [%- IF h.branchcode == cp.branchcode && h.found == \'W\' %]\r\n* [% h.biblio.title %], [% h.biblio.author %] ([% h.item.barcode %])\r\n    [%- END %]\r\n[%- END %]\r\n\r\nOnce you have arrived, please call your library or log into your account and click the \"Alert staff of your arrival\" button to let them know you are there.','email','default');
    "] at /usr/share/koha/lib/Koha/Plugins/Base.pm line 52

There have been some new columns added to the schema it looks like. Specifying which fields are being inserted resolves that error.

**Comment by kylemhall** [comment]
Thanks for letting me know! The latest version should have these issue fixed!
