### ISSUE TITLE
Set maximum amount out a patron can schedule a pickup

### ISSUE THREAD

**Issue by lisettescheer** [bywatersolutions/koha-plugin-curbside-pickup#4]
Currently a patron could schedule a pickup appointment in 1 year from now. It would be great if that could be limited, possibly based on a number of weeks or days?

**Comment by benjaminwd** [comment]
This would be great. I'm struggling to figure out how this might be executed in practice. I would also suggest blocking scheduling after a hold expires, but if there's multiple items on hold, that gets confusing. Can we also add an option where if a user schedules a pickup after one of their holds expires, they are notified of that at the time they attempt to create the appointment?

**Comment by tomascohen** [comment]
Old plugin version request.
