### ISSUE TITLE
Notification when patron has arrived

### ISSUE THREAD

**Issue by donnabws** [bywatersolutions/koha-plugin-curbside-pickup#9]
It would be helpful to have a way for staff to be automatically notified when a patron has marked themselves as arrived.  Perhaps either a popup box to alert staff when they go back to the home page of the staff interface, or something similar to the librarian notices at the bottom of the page like for patrons requesting updates/purchase suggestions.

**Comment by donnabws** [comment]
comment from library:
Unless you have something that comes up, no matter where you are in Koha, it seems someone is going to have to devote their time to watching for it.  If there were a devoted dashboard that staff could have on a computer, that would show arrivals, and maybe even make a noise, that would be ideal.  I'm just concerned staff will get busy and distracted with other tasks, and not think to check the page every 5 minutes or so to see if there is a new scheduled arrival.

**Comment by kylemhall** [comment]
I think a good solution would be to set up an auto-refresh on the "patron has arrived" tab, along with an audio alert. That way librarians would just leave that window in the background and would here the sound whenever a patron arrives. Thoughts?

**Comment by kylemhall** [comment]
Another possibility would be to add an api to get waiting patrons and write some javascript to show a popup/play a sound any time a patron has arrived. This would work without leaving a dedicated tab open for the patron has arrived page. On the downside, it would happen on all pages unless we added some kind of control to enable/disable the behavior, which really wouldn't be hard to also add.

**Comment by tomascohen** [comment]
Old plugin version request.
